require("dotenv").config();

module.exports = {
  DISCORD_TOKEN: process.env.DISCORD_TOKEN,
  MONGO_URI: process.env.MONGO_URI,
  ARRIVAL_CHANNEL_ID: process.env.ARRIVAL_CHANNEL_ID,
  TWITCH_CLIENT_ID: process.env.TWITCH_CLIENT_ID,
  TWITCH_CLIENT_SECRET: process.env.TWITCH_CLIENT_SECRET,
  TWITCH_ANNOUNCEMENT_CHANNEL_ID: process.env.TWITCH_ANNOUNCEMENT_CHANNEL_ID,
  TWITCH_USERNAME: process.env.TWITCH_USERNAME,
};
